version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: masterbot
      POSTGRES_USER: masterbot
      POSTGRES_PASSWORD: masterbot
    ports:
      - "82.115.43.200:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U masterbot"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: .
    command: sh -c "python scripts/wait_for_db.py && sh scripts/entrypoint_bot.sh"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # Hugging Face/Transformers cache to avoid re-downloading models
      HF_HOME: /models_cache
      TRANSFORMERS_CACHE: /models_cache
      # Configure local AI model (instruction-tuned)
      AI_MODEL_NAME: ${AI_MODEL_NAME:-google/flan-t5-base}
      AI_MAX_NEW_TOKENS: ${AI_MAX_NEW_TOKENS:-120}
    volumes:
      - .:/app
      - models_cache:/models_cache

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    command: sh -c "python scripts/wait_for_db.py && sh scripts/entrypoint_admin.sh"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  pgdata:
  models_cache:
