"""zones on User, Payout model, composite indexes

Revision ID: 7d5e94623ea9
Revises: dc5962138348
Create Date: 2025-08-08 23:38:27.568412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5e94623ea9'
down_revision: Union[str, None] = 'dc5962138348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
