"""add_location_updated_at_to_orders

Revision ID: add_location_updated_at
Revises: 7d5e94623ea9
Create Date: 2025-08-25 20:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_location_updated_at'
down_revision: Union[str, None] = '7d5e94623ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('location_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'location_updated_at')
    # ### end Alembic commands ###
