"""zones on User, Payout model, composite indexes

Revision ID: dc5962138348
Revises: 62d7e41dd991
Create Date: 2025-08-08 23:06:54.580181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc5962138348'
down_revision: Union[str, None] = '62d7e41dd991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('master_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_master', sa.Integer(), nullable=False),
    sa.Column('amount_service', sa.Integer(), nullable=False),
    sa.Column('amount_partner', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', name='payout_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_payouts_id'), 'payouts', ['id'], unique=False)
    op.create_index(op.f('ix_payouts_status'), 'payouts', ['status'], unique=False)
    op.create_index('ix_bids_order_created_at', 'bids', ['order_id', 'created_at'], unique=False)
    op.create_index('ix_orders_category_zone_status', 'orders', ['category', 'zone', 'status'], unique=False)
    op.add_column('users', sa.Column('zones', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zones')
    op.drop_index('ix_orders_category_zone_status', table_name='orders')
    op.drop_index('ix_bids_order_created_at', table_name='bids')
    op.drop_index(op.f('ix_payouts_status'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_id'), table_name='payouts')
    op.drop_table('payouts')
    # ### end Alembic commands ###
