"""add_referrer_id_to_users

Revision ID: f55f6c66afcf
Revises: 7d5e94623ea9
Create Date: 2025-08-15 22:24:05.485183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55f6c66afcf'
down_revision: Union[str, None] = '7d5e94623ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['referrer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referrer_id')
    # ### end Alembic commands ###
